"""empty message

Revision ID: 21174ade916a
Revises: 9439ed7fa997
Create Date: 2021-04-16 06:29:20.221674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21174ade916a'
down_revision = '9439ed7fa997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent')
    # ### end Alembic commands ###
